AWSTemplateFormatVersion: '2010-09-09'
Description: 'Seawater Frontend S3 Static Website Deployment for Media Account'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    Description: Environment name
  DevApiEndpoint:
    Type: String
    Default: 'https://5puux7rpx0.execute-api.us-east-2.amazonaws.com/dev'
    Description: Development backend API endpoint

Resources:
  # S3 Bucket for hosting static website
  SeawaterFrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'seawater-frontend-${Environment}-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD, POST, PUT, DELETE]
            AllowedOrigins: ['*']
            MaxAge: 3600

  # S3 Bucket Policy for public read access
  SeawaterFrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SeawaterFrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${SeawaterFrontendBucket}/*'

  # Lambda function for deployment automation
  DeploymentFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'seawater-frontend-deploy-${Environment}'
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt DeploymentFunctionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import json
          import cfnresponse
          
          def lambda_handler(event, context):
              try:
                  s3 = boto3.client('s3')
                  
                  bucket_name = event['ResourceProperties']['BucketName']
                  
                  if event['RequestType'] == 'Create' or event['RequestType'] == 'Update':
                      # Upload a simple index.html if none exists
                      try:
                          s3.head_object(Bucket=bucket_name, Key='index.html')
                      except:
                          s3.put_object(
                              Bucket=bucket_name,
                              Key='index.html',
                              Body='<html><body><h1>Seawater.io - Deployment in progress...</h1><p>Connected to development backend</p></body></html>',
                              ContentType='text/html'
                          )
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                  print(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})

  # IAM Role for deployment function
  DeploymentFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3DeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:PutObjectAcl
                Resource:
                  - !GetAtt SeawaterFrontendBucket.Arn
                  - !Sub '${SeawaterFrontendBucket}/*'

  # Custom resource to trigger initial deployment
  InitialDeployment:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt DeploymentFunction.Arn
      BucketName: !Ref SeawaterFrontendBucket

Outputs:
  FrontendBucketName:
    Description: Name of the S3 bucket for frontend hosting
    Value: !Ref SeawaterFrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucket'

  WebsiteURL:
    Description: URL of the S3 static website
    Value: !GetAtt SeawaterFrontendBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'

  S3BucketWebsiteURL:
    Description: URL of the S3 bucket website endpoint
    Value: !GetAtt SeawaterFrontendBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-S3WebsiteURL'