AWSTemplateFormatVersion: '2010-09-09'
Description: 'Seawater Frontend - Private S3 + CloudFront Distribution for Media Account (Simplified)'

Parameters:
  Environment:
    Type: String
    Default: 'prod'
    Description: Environment name for media account
  DomainName:
    Type: String
    Default: 'seawater.io'
    Description: Domain name for the application
  DevApiEndpoint:
    Type: String
    Default: 'https://5puux7rpx0.execute-api.us-east-2.amazonaws.com/dev'
    Description: Development backend API endpoint

Resources:
  # Private S3 Bucket for hosting static files (simplified)
  SeawaterPrivateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'seawater-frontend-private-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # CloudFront Origin Access Control (OAC)
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'seawater-oac-${Environment}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: 'Origin Access Control for Seawater Frontend'

  # S3 Bucket Policy to allow CloudFront access only
  SeawaterBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SeawaterPrivateBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${SeawaterPrivateBucket}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${SeawaterCloudFrontDistribution}'

  # CloudFront Distribution
  SeawaterCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt SeawaterPrivateBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
        Enabled: true
        DefaultRootObject: index.html
        Comment: !Sub 'Seawater Frontend Distribution - ${Environment} - Media Account'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # AWS Managed CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf  # AWS Managed CORS-S3Origin
          ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd  # AWS Managed SimpleCORS
        # Additional cache behaviors for static assets
        CacheBehaviors:
          - PathPattern: '/static/js/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          - PathPattern: '/static/css/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
        PriceClass: PriceClass_100  # Use only North America and Europe edge locations
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        HttpVersion: http2and3
        IPV6Enabled: true

Outputs:
  PrivateBucketName:
    Description: Name of the private S3 bucket for frontend hosting
    Value: !Ref SeawaterPrivateBucket
    Export:
      Name: !Sub '${AWS::StackName}-PrivateBucket'

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref SeawaterCloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'

  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt SeawaterCloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomain'

  WebsiteURL:
    Description: URL of the website
    Value: !Sub 'https://${SeawaterCloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'

  OriginAccessControlId:
    Description: CloudFront Origin Access Control ID
    Value: !Ref CloudFrontOriginAccessControl
    Export:
      Name: !Sub '${AWS::StackName}-OAC'